# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-29 18:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50, unique=True)),
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('website', models.TextField()),
                ('price', models.CharField(max_length=30)),
                ('work_hours', models.CharField(max_length=30)),
                ('location', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PlacesList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('places', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel_assist_app.Place')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=60, unique=True)),
                ('password', models.CharField(max_length=50)),
                ('places_lists', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel_assist_app.PlacesList')),
            ],
        ),
        migrations.AddField(
            model_name='city',
            name='places',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel_assist_app.Place'),
        ),
    ]
