# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-29 19:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travel_assist_app', '0002_auto_20180929_2205'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='places',
        ),
        migrations.AddField(
            model_name='place',
            name='city',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='travel_assist_app.City'),
            preserve_default=False,
        ),
    ]
