# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-29 19:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travel_assist_app', '0003_auto_20180929_2220'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='places_lists',
        ),
        migrations.AddField(
            model_name='place',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='placeslist',
            name='places_lists',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='travel_assist_app.User'),
            preserve_default=False,
        ),
    ]
