# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-27 11:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel_assist_app', '0007_auto_20181026_2026'),
    ]

    operations = [
        migrations.RenameField(
            model_name='placeslist',
            old_name='places_lists',
            new_name='user',
        ),
    ]
