# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-27 17:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_assist_app', '0008_auto_20181027_1431'),
    ]

    operations = [
        migrations.AddField(
            model_name='placeslist',
            name='list_id',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
